language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source=bincopy setup.py test
  - make test-sdist
after_success:
  coveralls
