language: python

python:
  - "3.6"
  - "3.8"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=bincopy setup.py test
  - make test-sdist

after_success:
  coveralls
